In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv(r"MachineLearningCVE\Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv")

In [3]:
df.head()

Destination Port   Flow Duration   Total Fwd Packets  \
0              54865               3                   2   
1              55054             109                   1   
2              55055              52                   1   
3              46236              34                   1   
4              54863               3                   2   

    Total Backward Packets  Total Length of Fwd Packets  \
0                        0                           12   
1                        1                            6   
2                        1                            6   
3                        1                            6   
4                        0                           12   

    Total Length of Bwd Packets   Fwd Packet Length Max  \
0                             0                       6   
1                             6                       6   
2                             6                       6   
3                             6                       6   
4                             0                       6   

    Fwd Packet Length Min   Fwd Packet Length Mean   Fwd Packet Length Std  \
0                       6                      6.0                     0.0   
1                       6                      6.0                     0.0   
2                       6                      6.0                     0.0   
3                       6                      6.0                     0.0   
4                       6                      6.0                     0.0   

   ...   min_seg_size_forward  Active Mean   Active Std   Active Max  \
0  ...                     20          0.0          0.0            0   
1  ...                     20          0.0          0.0            0   
2  ...                     20          0.0          0.0            0   
3  ...                     20          0.0          0.0            0   
4  ...                     20          0.0          0.0            0   

    Active Min  Idle Mean   Idle Std   Idle Max   Idle Min   Label  
0            0        0.0        0.0          0          0  BENIGN  
1            0        0.0        0.0          0          0  BENIGN  
2            0        0.0        0.0          0          0  BENIGN  
3            0        0.0        0.0          0          0  BENIGN  
4            0        0.0        0.0          0          0  BENIGN  

[5 rows x 79 columns]

In [4]:
df[" Label"].unique()

array(['BENIGN', 'DDoS'], dtype=object)

In [5]:
df = pd.concat([df,pd.read_csv(r"MachineLearningCVE\Friday-WorkingHours-Afternoon-PortScan.pcap_ISCX.csv")])

In [6]:
df[" Label"].unique()

array(['BENIGN', 'DDoS', 'PortScan'], dtype=object)

In [7]:
df = pd.concat([df,pd.read_csv(r"MachineLearningCVE\Friday-WorkingHours-Morning.pcap_ISCX.csv")])
df[" Label"].unique()

array(['BENIGN', 'DDoS', 'PortScan', 'Bot'], dtype=object)

In [8]:
df = pd.concat([df,pd.read_csv(r"MachineLearningCVE\Monday-WorkingHours.pcap_ISCX.csv")])
df[" Label"].unique()

array(['BENIGN', 'DDoS', 'PortScan', 'Bot'], dtype=object)

In [9]:
df = pd.concat([df,pd.read_csv(r"MachineLearningCVE\Thursday-WorkingHours-Afternoon-Infilteration.pcap_ISCX.csv")])
df[" Label"].unique()

array(['BENIGN', 'DDoS', 'PortScan', 'Bot', 'Infiltration'], dtype=object)

In [10]:
df = pd.concat([df,pd.read_csv(r"MachineLearningCVE\Thursday-WorkingHours-Morning-WebAttacks.pcap_ISCX.csv")])
df[" Label"].unique()

array(['BENIGN', 'DDoS', 'PortScan', 'Bot', 'Infiltration',
       'Web Attack � Brute Force', 'Web Attack � XSS',
       'Web Attack � Sql Injection'], dtype=object)

In [11]:
df = pd.concat([df,pd.read_csv(r"MachineLearningCVE\Tuesday-WorkingHours.pcap_ISCX.csv")])
df[" Label"].unique()

array(['BENIGN', 'DDoS', 'PortScan', 'Bot', 'Infiltration',
       'Web Attack � Brute Force', 'Web Attack � XSS',
       'Web Attack � Sql Injection', 'FTP-Patator', 'SSH-Patator'],
      dtype=object)

In [12]:
df = pd.concat([df,pd.read_csv(r"MachineLearningCVE\Wednesday-workingHours.pcap_ISCX.csv")])
df[" Label"].unique()

array(['BENIGN', 'DDoS', 'PortScan', 'Bot', 'Infiltration',
       'Web Attack � Brute Force', 'Web Attack � XSS',
       'Web Attack � Sql Injection', 'FTP-Patator', 'SSH-Patator',
       'DoS slowloris', 'DoS Slowhttptest', 'DoS Hulk', 'DoS GoldenEye',
       'Heartbleed'], dtype=object)

In [13]:
df=df.drop(columns=[' Fwd Header Length.1'],axis=1)

In [14]:
df[" Label"].unique()

array(['BENIGN', 'DDoS', 'PortScan', 'Bot', 'Infiltration',
       'Web Attack � Brute Force', 'Web Attack � XSS',
       'Web Attack � Sql Injection', 'FTP-Patator', 'SSH-Patator',
       'DoS slowloris', 'DoS Slowhttptest', 'DoS Hulk', 'DoS GoldenEye',
       'Heartbleed'], dtype=object)

In [15]:
df[' Label'].value_counts()

BENIGN                        2273097
DoS Hulk                       231073
PortScan                       158930
DDoS                           128027
DoS GoldenEye                   10293
FTP-Patator                      7938
SSH-Patator                      5897
DoS slowloris                    5796
DoS Slowhttptest                 5499
Bot                              1966
Web Attack � Brute Force         1507
Web Attack � XSS                  652
Infiltration                       36
Web Attack � Sql Injection         21
Heartbleed                         11
Name:  Label, dtype: int64

In [16]:
df.replace([np.inf, -np.inf], 0, inplace=True)

In [17]:
df.isna().sum()

 Destination Port              0
 Flow Duration                 0
 Total Fwd Packets             0
 Total Backward Packets        0
Total Length of Fwd Packets    0
                              ..
Idle Mean                      0
 Idle Std                      0
 Idle Max                      0
 Idle Min                      0
 Label                         0
Length: 78, dtype: int64

In [18]:
df99=df[df[' Label']=="BENIGN"]
df99.reset_index(drop=True, inplace=True)
print(df99.shape)
df1=df99.sample(n=115224, random_state=42)
print(df1.shape)
sampled_indices = df1.index
sampled_indices1 = df99.index
print(sampled_indices1.nunique())
print(df99.shape)
df2 = df99.drop(index = sampled_indices)
print(df2.shape)
df1.reset_index(drop=True, inplace=True)
df2.reset_index(drop=True, inplace=True)

(2273097, 78)
(115224, 78)
2273097
(2273097, 78)
(2157873, 78)


In [19]:
df99=df[df[' Label']=="PortScan"]
df3=df99.sample(n=115224, random_state=42)
sampled_indices1 = df99.index
print(sampled_indices1.nunique())
sampled_indices = df3.index
df4 = df99.drop(sampled_indices)
df3.reset_index(drop=True, inplace=True)
df4.reset_index(drop=True, inplace=True)
df1=pd.concat([df3,df1])
df2=pd.concat([df4,df2])

158930


In [20]:
df99=df[df[" Label"]=="DDoS"]
df1=pd.concat([df1,df99.iloc[:115224,:]])
df2=pd.concat([df2,df99.iloc[115224:,:]])


In [21]:
df99=df[df[' Label']=="DoS Hulk"]
df3=df99.sample(n=115224, random_state=42)
sampled_indices = df3.index
df4 = df99.drop(sampled_indices)
df3.reset_index(drop=True, inplace=True)
df4.reset_index(drop=True, inplace=True)
df1=pd.concat([df3,df1])
df2=pd.concat([df4,df2])

In [22]:
Label=df1[' Label']
Label=Label.map({"BENIGN":0,"DoS Hulk":1,"PortScan":2,"DDoS":3})
Label.unique()
df1.drop(" Label",inplace=True,axis=1)
df1=pd.concat([df1,Label],axis=1)
Label=df2[' Label']
Label=Label.map({"BENIGN":0,"DoS Hulk":1,"PortScan":2,"DDoS":3})
Label.unique()
df2.drop(" Label",inplace=True,axis=1)
df2=pd.concat([df2,Label],axis=1)

In [23]:
df1[" Label"].unique()

array([1, 2, 0, 3], dtype=int64)

In [24]:
df2[" Label"].unique()

array([1, 2, 0, 3], dtype=int64)

In [25]:
data = df1
data_test=df2
data_test=data_test[data_test[" Label"]!=0]

In [26]:
data.fillna(0,inplace=True)

In [27]:
import numpy as np
data_test=data_test[~np.isinf(data_test).any(axis=1)]
data.replace([np.inf, -np.inf], 0, inplace=True)

In [28]:
Y=data[" Label"]
Y.head()

0    1
1    1
2    1
3    1
4    1
Name:  Label, dtype: int64

In [29]:
data.drop(columns=[" Label"],inplace=True)

In [30]:
Y_test=data_test[" Label"]

In [31]:
data_test.drop(columns=[" Label"],inplace=True)

In [32]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 250,criterion="entropy",random_state=11)


classifier.fit(data,Y)

RandomForestClassifier(criterion='entropy', n_estimators=250, random_state=11)

In [33]:
data_test.fillna(0,inplace=True)
y_pred = classifier.predict(data_test)
y_pred

array([1, 1, 1, ..., 3, 3, 3], dtype=int64)

In [34]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report,accuracy_score

In [35]:
cm = confusion_matrix(Y_test,y_pred)
print(cm)

[[     0      0      0      0]
 [    37 115806      6      0]
 [    16      6  43684      0]
 [    22     25      0  12756]]


In [36]:
accuracy_score(Y_test,y_pred)

0.9993501897213939

In [37]:
import warnings
warnings.filterwarnings('ignore')
print(classification_report(Y_test,y_pred))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
           1       1.00      1.00      1.00    115849
           2       1.00      1.00      1.00     43706
           3       1.00      1.00      1.00     12803

    accuracy                           1.00    172358
   macro avg       0.75      0.75      0.75    172358
weighted avg       1.00      1.00      1.00    172358



In [38]:
import joblib

# Assuming you have a trained Random Forest model called 'classifier'
# Save the model to a file
joblib.dump(classifier, 'cic_random_forest_model1.pkl')

['cic_random_forest_model1.pkl']